apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx_deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        run: nginx_deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        port:
        - containerPort: 80
        resources: {}
status: {}
